import "~/styles/globals.css";
import type { Metadata } from "next";
import { Providers } from "./providers";
import { Geist } from "next/font/google";
import { AppSidebar } from "~/features/app-sidebar";
import { SidebarInset, SidebarProvider, Toaster } from "~/shared/components";

export const metadata: Metadata = {
  title: "Hono T3",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="pt-BR" className={`${geist.variable}`} suppressHydrationWarning>
      <body className="antialiased">
        <Providers>
          <SidebarProvider className="container max-w-7xl mx-auto h-screen">
            <AppSidebar />
            <SidebarInset>{children}</SidebarInset>
          </SidebarProvider>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
