import "~/styles/globals.css";
import type { Metadata } from "next";
import { Provider } from "./provider";
import { Geist } from "next/font/google";
import { Container, Content, Header, Sidebar } from "~/layouts";

export const metadata: Metadata = {
  title: "Hono T3",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="pt-BR" className={`${geist.variable}`} suppressHydrationWarning>
      <body className="antialiased dark:!bg-black">
        <Provider>
          <Container className="flex flex-col sm:grid sm:grid-cols-[auto_1fr] sm:grid-rows-[auto_1fr]">
            <Header className="border-b" />
            <Sidebar className="w-50 border-r row-start-1 row-end-3" />
            <Content>{children}</Content>
          </Container>
        </Provider>
      </body>
    </html>
  );
}
